### ISSUE TITLE
SCED code for foreign language and literature

### ISSUE THREAD

**Issue by philbarker** [CEDStandards/CEDS-Ontology#39]
The enumeration for School Courses for the Exchange of Data Course Subject Area (C001518) is missing Foreign Language and Literature. There is also a gap in the URI numbering where it would fit (NI001518118409). Is this an error

**Comment by aemnathanclinton** [comment]
The "Foreign Language and Literature" subject area was reclassified, which is why you do not see it in CEDS V12.  Below is a description from SCED's FAQ:

From https://nces.ed.gov/forum/pdf/sced_faq_508.pdf : 

**Where are Foreign Language and Literature courses that were previously included in Subject Area 06
located?**
SCED Version 4 reclassified Foreign Language and Literature courses in the newly created Subject Area 24:
World Languages. This reclassification was necessary to update existing courses and add new courses that were
SCED Frequently Asked Questions 6 recommended by subject matter experts and SCED users.

**Comment by philbarker** [comment]
Thank you @aemnathanclinton
